server:
  port: 8042
spring:
  application:
    name: case-02-event-listener
  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics